schema_version = "1.0.0"

id = "blenderdefender_spm"
name = "Super Project Manager (SPM)"
version = "1.3.1"
tagline = "Manage and setup your projects the easy way"
maintainer = "Blender Defender"
website = "https://github.com/PidgeonTools/SuperProjectManager/issues"

type = "add-on"
blender_version_min = "4.2.0"
license = ["SPDX:GPL-3.0-or-later"]

[build]
paths_exclude_pattern = [".*", "*.pyc", "test_*.py"]
